#!/usr/bin/env python3
"""Generate docs/LEGACY_SECURITY_LINEAGE.md from the authoritative registry.

The table is produced from ``configs/legacy_security_lineage.yaml`` and
``metadata/legacy_coverage.csv`` so the document can never drift from the data.

The final column, ``successor stitched``, is generated as ``NO`` for every
merger/acquisition into another issuer.  A test asserts this.

Usage:
    python scripts/generate_legacy_lineage_doc.py
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

_spec = importlib.util.spec_from_file_location(
    "download_yfinance_daily", REPO_ROOT / "scripts" / "download_yfinance_daily.py")
dl = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dl)

UNIVERSE_CFG = "configs/nifty50_legacy_user_supplied.yaml"
LINEAGE_CFG = "configs/legacy_security_lineage.yaml"
OUT = REPO_ROOT / "docs" / "LEGACY_SECURITY_LINEAGE.md"

# event_type -> (resolved_company, human identity_status)
STATUS = {
    "unchanged": "same surviving security",
    "same_security_rename": "same security, renamed",
    "statutory_continuation": "same security, statutory/ticker-format",
    "demerger": "same shell, demerger break",
    "merger_into_other_company": "MERGED INTO ANOTHER ISSUER",
    "acquired_and_merged": "ACQUIRED AND MERGED",
    "delisted": "delisted",
    "unresolved": "unresolved",
}


def legacy_root() -> Path:
    import os
    root = os.environ.get("AGENTIC_YFINANCE_LEGACY_ROOT")
    if root:
        return Path(root)
    return Path(os.environ["AGENTIC_DATA_ROOT"]) / "yfinance_legacy_nifty50_2000_2025"


def esc(text: str) -> str:
    """Make a value safe for a markdown table cell."""
    return str(text or "").replace("|", "\\|").replace("\n", " ").strip() or "-"


def main() -> int:
    labels = dl.load_universe(REPO_ROOT, UNIVERSE_CFG)
    lineage = dl.load_lineage(REPO_ROOT, LINEAGE_CFG)
    root = legacy_root()
    cov_path = root / "metadata" / "legacy_coverage.csv"
    cov = pd.read_csv(cov_path).set_index("legacy_label") if cov_path.is_file() else None

    lines: list[str] = [
        "# Corporate action research summary — legacy NIFTY-50 universe",
        "",
        "Generated by `scripts/generate_legacy_lineage_doc.py` from",
        f"`{LINEAGE_CFG}` and `{UNIVERSE_CFG}`. Do not edit by hand.",
        "",
        "## Reading the table",
        "",
        "* **identity_status** distinguishes a *same legal security* (whose price",
        "  history is continuous and is used) from a *different legal entity*",
        "  (whose history must end).",
        "* **successor stitched** is `NO` everywhere by policy. For a company that",
        "  merged into another issuer, the successor's prices are recorded in",
        "  `metadata/successor_lineage_plan.csv` for a future optional experiment",
        "  and are **never** placed in the canonical workbook.",
        "* An empty `Yahoo symbol` with an empty start/end means no legitimate",
        "  same-security Yahoo history exists; the sheet is intentionally empty.",
        "",
        "## All 50 securities",
        "",
        "| supplied_label | resolved_company | identity_status | Yahoo symbol | start | end | corporate event | successor | successor stitched |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    counts: dict[str, int] = {}
    for label in labels:
        e = lineage[label]
        ev = e.get("event_type")
        counts[STATUS.get(ev, ev)] = counts.get(STATUS.get(ev, ev), 0) + 1
        if cov is not None and label in cov.index:
            row = cov.loc[label]
            start = row["first_date"] if isinstance(row["first_date"], str) else "-"
            end = row["last_date"] if isinstance(row["last_date"], str) else "-"
        else:
            start = end = "-"
        resolved = (e.get("current_or_final_company_name")
                    or e.get("historical_company_name"))
        # The successor is listed ONLY to document what it is NOT used for.
        lines.append(
            f"| `{esc(label)}` | {esc(resolved)} | {esc(STATUS.get(ev, ev))} | "
            f"`{esc(e.get('primary_yahoo_candidate') or '— none —')}` | {esc(start)} | "
            f"{esc(end)} | {esc(ev)} @ {esc(e.get('event_date') or 'n/a')} | "
            f"{esc(e.get('successor_security') or '—')} | **NO** |")

    # ---- event detail for the non-trivial cases ----
    lines += ["", "## Event detail for securities with a corporate event", ""]
    for label in labels:
        e = lineage[label]
        ev = e.get("event_type")
        if ev in ("unchanged",):
            continue
        same = e.get("same_legal_security")
        lines += [
            f"### `{label}` — {ev}",
            "",
            f"- **Historical name:** {e.get('historical_company_name')}",
            f"- **Current / final:** {e.get('current_or_final_company_name')}",
            f"- **Event date:** {e.get('event_date') or 'n/a'}",
            f"- **Same legal security:** {same}",
            f"- **Accepted Yahoo symbol:** `{e.get('primary_yahoo_candidate') or 'none — do_not_download'}`",
            f"- **Download policy:** `{e.get('primary_download_policy')}`",
            f"- **Confidence:** {e.get('confidence')}",
            f"- **Successor (recorded, never appended):** {e.get('successor_security') or 'n/a'}",
            "",
            (e.get("evidence_notes") or "").strip(),
            "",
        ]

    lines += [
        "## Totals",
        "",
        "| Identity status | Count |",
        "|---|---|",
    ]
    for k, v in sorted(counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {k} | {v} |")
    lines += [
        f"| **Total** | **{sum(counts.values())}** |",
        "",
        "## Policy statement",
        "",
        "Successor prices were **never** appended to any historical series. No",
        "series was forward-filled after delisting, no last close was repeated,",
        "and no synthetic pre-listing observation was created. Where a security",
        "ceased to exist, its canonical sheet is empty apart from the header row.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(labels)} securities, {OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
